#!/bin/sh


echo "$OSTYPE" | grep -q "darwin" && escape="\033" || escape="\e"

# set colors
cn="`echo -e '\r'$escape'[0;1m'`" # normal
cr="`echo -e '\r'$escape'[1;7m'`" # reverse

# keys
au="`echo -e $escape'[A'`" # arrow up
ad="`echo -e $escape'[B'`" # arrow down
ec="`echo -e $escape`"   # escape
nl="`echo -e '\n'`"   # newline

tput civis

variables="$(printenv | sed 's;=.*;;' | sort)"
tn=$(echo "$variables" | wc -w)



{

  cp=1 # current position

  end=false

  while ! $end; do
    tput civis
    echo  ""

    index=1
    while [ "$index" -ne 6 ]; do
      variable=$(echo "$variables" | sed -n $index'p')
      if [[ $cp == $index ]]; then
        echo -n "$cr > $variable  $cn"
      else
        echo -n "   $variable  "
      fi
      [ "$index" -ne 5 ] && echo ""
      index=$((index + 1))
    done

    tput cuu 5
    echo -ne "\rFilter variable: $query"

    tput cnorm
     read -sn 1 key
     [[ "$key" == "$ec" ]] &&
     {
        read -sn 2 k2
        key="$key$k2"
     }

     tput civis
     case "$key" in

        "$au")
           cp=$(( cp - 1 ))
           [[ $cp == 0 ]] && cp=5
           ;;

        "$ad")
           cp=$(( cp + 1 ))
           [[ $cp == 6 ]] && cp=1
           ;;

        "$nl")
           si=true
           end=true
           ;;

        "q")
           si=false
           end=true
           ;;

        *)
          query="$query$key"

     esac

 #     echo "- $key"

  done

  tput cud $(( tn - 1 ))
  tput cnorm # unhide cursor
  echo "$cn" # normal colors
} >&2

$si && eval "echo \$$cp"


