#!/bin/sh


echo "$OSTYPE" | grep -q "darwin" && escape="\033" || escape="\e"

# set colors
cn="`echo -e '\r'$escape'[0;1m'`" # normal
cr="`echo -e '\r'$escape'[1;7m'`" # reverse

# keys
au="`echo -e $escape'[A'`" # arrow up
ad="`echo -e $escape'[B'`" # arrow down
ec="`echo -e $escape`"   # escape
nl="`echo -e '\n'`"   # newline


variables="$(printenv | sed 's;=.*;;' | sort)"
tn=$(echo "$variables" | wc -w)
echo $tn
{

  cp=1 # current position

  end=false

  while ! $end; do

     i=1
     echo "$variables" | head -5 | while read variable; do
       echo -n "$cn"
       [[ $cp == $i ]] && echo -n "$cr"
       echo " $variable "
       i=$((i+1))
     done

     read -sn 1 key
     [[ "$key" == "$ec" ]] &&
     {
        read -sn 2 k2
        key="$key$k2"
     }
     case "$key" in

        "$au")
           cp=$(( cp - 1 ))
           [[ $cp == 0 ]] && cp=$tn
           ;;

        "$ad")
           cp=$(( cp + 1 ))
           [[ $cp == $(( tn + 1 )) ]] && cp=1
           ;;

        "$nl")
           si=true
           end=true
           ;;

        "q")
           si=false
           end=true
           ;;

     esac

     tput cuu 5
      echo "- $key"

  done

  tput cud $(( tn - 1 ))
  tput cnorm # unhide cursor
  echo "$cn" # normal colors
} >&2

$si && eval "echo \$$cp"


